#!/bin/sh
HostGroup="mj-ubuntu0";
SoftwareUrl="/home/ppc/SOFTWARES";
HadoopUrl="/local/HADOOP";
stop-all.sh

for i in 2 3 6 7
do
        ssh $HostGroup$i "rm -fr $SoftwareUrl"
        echo "[sys mesg] (Done) ssh $HostGroup$i rm -fr $SoftwareUrl";
        scp -r $SoftwareUrl ppc@$HostGroup$i:/local/
        echo "[sys mesg] (Done) scp -r $SoftwareUrl ppc@$HostGroup$i:/local/";

        ssh $HostGroup$i "rm -fr $HadoopUrl"
        echo "[sys mesg] (Done) ssh $HostGroup$i rm -fr $HadoopUrl"
        ssh $HostGroup$i "mkdir $HadoopUrl"
        echo "[sys mesg] (Done) ssh $HostGroup$i mkdir $HadoopUrl"

        ssh $HostGroup$i "rm -fr $HadoopUrl/TMP"
        echo "[sys mesg] (Done) ssh $HostGroup$i rm -fr $HadoopUrl/TMP"
        ssh $HostGroup$i "mkdir $HadoopUrl/TMP"
        echo "[sys mesg] (Done) ssh $HostGroup$i mkdir $HadoopUrl/TMP"

        ssh $HostGroup$i "rm -fr $HadoopUrl/HISTORY"
        echo "[sys mesg] (Done) ssh $HostGroup$i rm -fr $HadoopUrl/HISTORY"
        ssh $HostGroup$i "mkdir $HadoopUrl/HISTORY"
        echo "[sys mesg] (Done) ssh $HostGroup$i mkdir $HadoopUrl/HISTORY"

        ssh $HostGroup$i "rm -fr $HadoopUrl/HDFS_NAME"
        echo "[sys mesg] (Done) ssh $HostGroup$i rm -fr $HadoopUrl/HDFS_NAME"
        ssh $HostGroup$i "mkdir $HadoopUrl/HDFS_NAME"
        echo "[sys mesg] (Done) ssh $HostGroup$i mkdir $HadoopUrl/HDFS_NAME"

        ssh $HostGroup$i "rm -fr $HadoopUrl/HDFS_DATA"
        echo "[sys mesg] (Done) ssh $HostGroup$i rm -fr $HadoopUrl/HDFS_DATA"
        ssh $HostGroup$i "mkdir $HadoopUrl/HDFS_DATA"
        echo "[sys mesg] (Done) ssh $HostGroup$i mkdir $HadoopUrl/HDFS_DATA"

        ssh $HostGroup$i "rm -fr $HadoopUrl/MAPRED"
        echo "[sys mesg] (Done) ssh $HostGroup$i rm -fr $HadoopUrl/MAPRED"
        ssh $HostGroup$i "mkdir $HadoopUrl/MAPRED"
        echo "[sys mesg] (Done) ssh $HostGroup$i mkdir $HadoopUrl/MAPRED"

        ssh $HostGroup$i "chmod -R 755 $HadoopUrl"
        echo "[sys mesg] (Done) ssh $HostGroup$i chmod -R 755 $HadoopUrl"
done


hadoop namenode -format

